example/screens/ImageScreen.js
example/yarn.lock
package-lock.json
src/components/image/rkModalImg.js
src/components/rkComponent.js

- [+] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
- [+] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.
Fixes an issue when rkModalImg containing more than 10 items doesn't render initial clicked item.
See [issue](https://github.com/akveo/react-native-ui-kitten/issues/98).
**Notes:** this pull request should override the [previous one](https://github.com/akveo/react-native-ui-kitten/pull/114), which doesn't resolve this issue completely for Android.

fix(rkModalImg): container with more than 10 items render. Closes #98

---

CHANGELOG.md
docs/structure.ts
example/screens/TabScreen.js
package.json
src/components/avoidKeyboard/rkAvoidKeyboard.js
src/components/button/rkButton.js
src/components/card/rkCard.js
src/components/choice/rkChoice.js
src/components/choiceGroup/rkChoiceGroup.js
src/components/gallery/rkGallery.js
src/components/gallery/rkGalleryGrid.js
src/components/gallery/rkGalleryImage.js
src/components/image/rkModalImg.js
src/components/picker/rkPicker.js
src/components/switch/rkSwitch.android.js
src/components/switch/rkSwitch.ios.js
src/components/tab/rkTabView.js
src/components/text/rkText.js
src/components/textinput/rkTextInput.js

**Bug Fixes:**
* **rkTextInput:** non-editable rkTextInput crash on Android ([e755ce1](https://github.com/akveo/react-native-ui-kitten/commit/e755ce1))
* **rkModalImg:** more than 10 items render ([c98d45c](https://github.com/akveo/react-native-ui-kitten/commit/c98d45c))
* **rkCard:** nullable subview render ([0275291](https://github.com/akveo/react-native-ui-kitten/commit/0275291))
* **rkChoice:** antialiased render on Android ([c86d57c](https://github.com/akveo/react-native-ui-kitten/commit/c86d57c))
**Features:**
* **build:** eslint integration and project adopt ([24d268b](https://github.com/akveo/react-native-ui-kitten/commit/24d268b))
* **build:** add expo 27 and RN 0.56 support ([8c8b987](https://github.com/akveo/react-native-ui-kitten/commit/8c8b987))
* **rkSwitch:** component …

Release 3.1.0

---

src/components/switch/rkSwitch.android.js

There is thumb animation when a user starts a gesture. And if RkSwitch is included into another component with its own pan responder (like ScrollView) the animation will be not canceled if gestures will be intercepted.

fix(RkSwitch): Fix incorrect thumb animation in case if gesture was intercepted by parent view

---

src/components/button/rkButton.js

Replace the type of `contentStyle` from `ViewPropTypes.style` to `RkText.propTypes.style` to resolve the [issue#177](https://github.com/akveo/react-native-ui-kitten/issues/177)

fix(rkText): style prop definition. Closes #177

---

package.json
src/framework/theme/component/style/styleConsumer.component.tsx
src/framework/theme/component/theme/themeConsumer.component.tsx
src/framework/ui/index.ts
src/playground/package.json
src/playground/src/app.component.tsx
src/playground/src/navigation/index.ts
src/playground/src/navigation/navigation.component.tsx
src/playground/src/ui/component/index.ts
src/playground/src/ui/component/sample.component.tsx
src/playground/src/ui/screen/home.component.tsx
src/playground/src/ui/screen/index.ts
src/playground/src/ui/screen/sample.component.tsx

* integrates react-navigation for building playground app
* fixes several related bugs

feat(playground): home screen. Closes #203

---

src/framework/theme/service/mappingUtil.service.ts
src/framework/theme/service/styleUtil.service.ts
src/framework/theme/tests/__snapshots__/style.spec.ts.snap
src/framework/theme/tests/config/mapping.json
src/framework/theme/tests/style.spec.ts

* fixes ordering of mapping application

fix(theme): mapping application order. Closes #218

---

src/framework/theme/component/mapping/index.ts
src/framework/theme/component/mapping/mappingContext.ts
src/framework/theme/component/mapping/mappingProvider.component.tsx
src/framework/theme/component/style/index.ts
src/framework/theme/component/style/styleConsumer.component.tsx
src/framework/theme/component/style/styleProvider.component.tsx
src/framework/theme/component/theme/index.ts
src/framework/theme/component/theme/themeConsumer.component.tsx
src/framework/theme/component/theme/themeContext.ts
src/framework/theme/component/theme/themeProvider.component.tsx
src/framework/theme/service/style/style.service.ts
src/framework/theme/service/style/style.spec.ts
src/framework/theme/service/style/styleConsumer.spec.tsx

refactor(theme): optimize module imports

---

src/framework/ui/checkbox/checkbox.component.tsx
src/framework/ui/checkbox/checkbox.spec.config.ts
src/framework/ui/checkbox/checkbox.spec.tsx
src/framework/ui/drawable/checkmark/checkmark.component.tsx
src/framework/ui/index.ts
src/playground/src/ui/screen/checkbox.component.tsx
src/playground/src/ui/screen/index.ts

implements `CheckBox` component

feat(ui): checkbox component

---

src/playground/src/app.component.tsx
src/playground/src/navigation/navigation.component.tsx
src/playground/src/ui/screen/home.component.tsx
src/playground/src/ui/screen/radio.component.tsx
src/playground/src/ui/screen/radioGroup.component.tsx

I'd like each component inside `framework` to use the same code style

refactor(playground): update playground to use typescript

---

src/framework/theme/component/application/applicationProvider.component.tsx
src/framework/ui/popover/popover.component.tsx
src/framework/ui/tooltip/tooltip.component.tsx

* Fixes issue when `StyleConsumer` did not received context props after `setState` have been called
* Refactors `Tooltip` to use framework's `Text` component

fix(theme): style provider - reduce setState calls

---

src/framework/ui/overflowMenu/overflowMenu.component.tsx
src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
src/framework/ui/popover/popover.component.tsx

* Removes useless render of popover while it is invisible
* Refactors components built on `Popover`

fix(ui): popover visibility

---

src/framework/ui/common/mapping.json
src/framework/ui/tooltip/tooltip.component.tsx
src/playground/src/ui/screen/tooltip.component.tsx

refactor(ui): apply tooltip mappings

---

src/framework/ui/common/mapping.json
src/framework/ui/radio/radio.component.tsx
src/framework/ui/radio/radio.spec.tsx.snap
src/playground/src/ui/screen/radio.component.tsx

* Fixes `onPress` when text is pressed

refactor(ui): apply radio mappings

---

src/framework/ui/index.ts
src/framework/ui/tab/tabView.component.tsx

* Exports `TabView` `children` prop props

fix(ui): export tab-view children props

---

src/framework/theme/application/application.spec.tsx.snap
src/framework/theme/support/tests/theme.json
src/framework/theme/theme/theme.service.ts
src/framework/theme/theme/theme.spec.tsx

* Adds ability to reference theme values

feat(theme): referencing values

---

docs/src/guides/install-into-existing.md
docs/src/guides/start.md
docs/src/guides/theme-customize-component.md
docs/src/guides/theme-system.md
docs/src/guides/theme-using-mapping.md

fix(docs): proper cross sections links

---

src/framework/theme/style/styleConsumer.service.ts

Adds custom console warnings for incorrect component usage
- Missing `ApplicationProvider` #469 
- Incorrect semantic property values
- Missing semantic property meta
This will also make components to apply default styles in case incorrect where provided
Closes #469

feat(ui): add custom warnings for incorrect component usage

---

README.md

This is just a simple edit to the readme. 
It's just missing a `>`
When I was setting up ui-kitten, I ran into an error after copying the quick-start code.

add missing `>` to example code in the readme

---

package-lock.json
package.json
src/playground/app.json
src/playground/package-lock.json
src/playground/package.json

* Bumps Expo to SDK 34. Closes #554 
This adds `react-native-gesture-handler` and `react-native-reanimated` modules to a playground dependencies, because starting from SDK 34 it's not included in Expo.

build(common): update expo to sdk 34

---

src/framework/ui/menu/subMenu.component.tsx
src/playground/metro.config.js

fix(ui): sub-menu components items onPress handling fix

---

package.json
scripts/environment/set-env.js
scripts/environment/set-env.sh

Related issue: #645 
Refactors `set-env` script to node executable, which makes possible to run playground on Windows

refactor(script): set-env script with node

---

src/framework/ui/buttonGroup/buttonGroup.component.tsx

fix(ui): button-group render issues

---

src/framework/ui/modal/modal.component.tsx

This closes #699
But the issue may persist for the interactive window resizing since there is no way to do something like
```js
window.addEventListener('resize', () => { ... });
``` 
Related issue https://github.com/necolas/react-native-web/issues/60

fix(ui): modal center positioning

---

package.json
src/components/theme/modal/modalPanel.spec.tsx.snap
src/components/ui/toggle/toggle.spec.tsx
src/playground/app.json
src/playground/metro.config.js
src/playground/package.json
yarn.lock

**Playground:**
Bump Expo to SDK 36 (Fast Refresh 🎉)
**Root package:**
Bump react-native and related dependencies to 0.61.4 in order to fit playground

feat(playground): upgrade to expo sdk 36

---

src/components/ui/autocomplete/autocomplete.component.tsx
src/components/ui/datepicker/baseDatepicker.component.tsx
src/components/ui/datepicker/datepicker.component.tsx
src/components/ui/datepicker/rangeDatepicker.component.tsx
src/components/ui/modal/modal.component.tsx
src/components/ui/overflowMenu/overflowMenu.component.tsx
src/components/ui/popover/popover.component.tsx
src/components/ui/select/select.component.tsx
src/components/ui/tooltip/tooltip.component.tsx

Hides modals when `componentWillUnmount` is called. 
Also adds `show` and `hide` methods
Closes #813 
Closes #808 
Closes #735

feat(components): add direct manipulation methods to modal components

---

src/components/ui/calendar/rangeCalendar.spec.tsx

Modifies Range Calendar spec so that there is no way to perform date selection from previous month during the test case

test(components): fix range-date-picker spec

---

src/components/ui/topNavigation/topNavigation.component.tsx

In the second property it should be **accesoryRight** but it says **accesoryLeft** instead thus repeating **accesoryLeft** twice.
Before:
```typescript
* @property {() => ReactElement} accessoryLeft - Function component
* to render to the left edge the top navigation.
*
* @property {() => ReactElement} accessoryLeft - Function component
* to render to the right edge the top navigation.
```
After:
```typescript
* @property {() => ReactElement} accessoryLeft - Function component
* to render to the left edge the top navigation.
*
* @property {() => ReactElement} accessoryRight - Function component
* to render to the right edge the top navigation.
```

docs(topNavigation): fix typo for accesoryRight

---

src/components/ui/icon/icon.component.tsx
src/components/ui/icon/icon.spec.tsx
src/components/ui/icon/iconAnimation.ts
src/showcases/components/icon/iconAnimation.component.tsx

In our app we render a lot lists with hundreds or thousands of items. Each list item has an icon, but list rendering is slowed down by the icons animating. We don't care much for the animation and would like an easy way to disable the animation.

feat(icon): add null as a valid animation 

---

docs/src/articles/design-system/customize-mapping.md

A parameter of iterest should be declared here -> A parameter of interest should be declared here.

Correction of the word in customized mappings.

---

src/components/ui/calendar/baseCalendar.component.tsx
src/components/ui/calendar/components/calendarDateContent.component.tsx
src/date-fns/dateFnsDate.service.spec.ts
src/date-fns/dateFnsDate.service.ts
src/date-fns/package.json
src/moment/momentDate.service.ts
yarn.lock

Update @ui-kitten/date-fns package to use date-fns v2.
- Adds ability to parse dates with specified format
- Uses [Unicode Tokens](https://date-fns.org/v2.17.0/docs/Unicode-Tokens)
- [Full Changelog](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#200---2019-08-20)

feat(date-fns): bump date-fns to v2

---

src/components/ui/modal/modal.component.tsx

The solutions is quite simple - I just render new modal with new id. I dont think there would be a possibility to apply new position to old one. If you think we can apply new position for the modal - let me know pls
Closes #1132

fix: add change orientation event with modal render

---

src/showcases/components/checkbox/checkboxIndeterminate.component.tsx

On clicking the parent checkbox, it should become checked if all children checkboxes are checked. Currently, it stays indeterminate.

Fix UX issue with Checkbox Indeterminate showcase

---

src/metro-config/index.ts
src/metro-config/services/eva-config.service.ts

Metro bundler runs indefinitely in CI/CD environments when using ui-kitten's metro config because a file watcher is opened. This change provides a way to disable the file watcher in production builds as the mapping is not likely to change. This fixes #1410

feat(metro): add support for disabling custom mapping file watcher

---

src/components/theme/style/style.spec.tsx
src/components/theme/style/styled.tsx
src/components/theme/theme/theme.spec.tsx
src/components/theme/theme/withStyles.tsx

Currently most of the components re-render because of parent render. Using `PureComponent` on `styled` HOC resolve the issue.
The components will be re-rendered only after props, theme or inner state changes
Closes #1400

fix: prevent styled component from redundant re-renders

---

src/components/ui/calendar/components/calendarHeader.component.tsx

turn back re-render of calendar header (was broken by #1489)

fix (calendar): re-render header on arrow press

---

docs/src/articles/guides/getting-started.md

In order to solve the bug that you bump into as soon as you add `ui-kitten` library to an expo project and try to see the the project in Expo for Web https://github.com/akveo/react-native-ui-kitten/issues/996, this super clean solution needs to be part of the docs, thus this PR. https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-790975093

add needed step to fix issue with Expo for Web

---

src/components/ui/calendar/components/picker/calendarPicker.component.tsx
src/components/ui/calendar/components/picker/calendarPickerCell.component.tsx
src/components/ui/calendar/rangeCalendar.component.tsx
src/components/ui/calendar/service/calendarData.service.ts
src/components/ui/calendar/service/rangeDate.service.spec.ts
src/components/ui/calendar/service/rangeDate.service.ts
src/components/ui/calendar/type.ts

allow to pick one day as completed range, closes #1564

fix (rangePicker): allow to pick one day as completed range

---

docs/src/articles/guides/configure-navigation.md

Quoting the docs "Stack Navigator: These changes affect users of @react-navigation/stack package.
* headerMode="none" is removed in favor of headerShown: false
"
Link to docs:
https://reactnavigation.org/docs/upgrading-from-5.x/#deprecations

docs: navigation guide, deprecated prop

---

src/components/devsupport/components/touchableWithoutFeedback.component.tsx
src/components/ui/input/input.component.tsx

Removes outline and fix for double tab keyboard behaviour for Input component when used in web, closes #1422

fix(input): fixed double tab for Input component for react-native-web

---

docs/src/articles/guides/getting-started.md

docs: getting started guide, malformed json example (#1605)
Fixes #1605 Added missing bracket to JSON example within Getting Started > Manual Installation guide
Adds a missing bracket to the app.json web configuration example within the "Getting Started" > "Manual Installation" guide.

docs: getting started guide, malformed json example (#1605)

---

docs/src/articles/guides/improving-performance.md
src/metro-config/index.ts

fix: metro-config is not working in bare react native project
