akveo/react-native-ui-kitten

- src/styles/styleSheet.js
> fix mistype in RkStyleSheer

- src/components/tab/rkTab.js
- src/styles/typeManager.js
> chore(common): fix class static properties #35

- src/components/button/rkButton.js
Add capability pass custom touchable in rkButton
> feat(rkButton): add capability pass custom touchable

- example/screens/CardScreen.js
- src/components/card/rkCard.js
- [+] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
- [+] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.
Fixes rkCard crash when contains null subviews.
See [issue](https://github.com/akveo/react-native-ui-kitten/issues/119)
> fix(rkCard): null subview render. Closes #119

- example/screens/ChoiceScreen.js
- src/components/choice/rkChoice.js
- src/components/choice/types.js
- [+] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
- [+] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.
Antialiased border render on Android with type is 'radio'.
See [issue](https://github.com/akveo/react-native-ui-kitten/issues/100).
> fix(rkChoice): antialiased border render on Android. Closes #100

- CHANGELOG.md
- docs/structure.ts
- example/screens/TabScreen.js
- package.json
- src/components/avoidKeyboard/rkAvoidKeyboard.js
- src/components/button/rkButton.js
- src/components/card/rkCard.js
- src/components/choice/rkChoice.js
- src/components/choiceGroup/rkChoiceGroup.js
- src/components/gallery/rkGallery.js
- src/components/gallery/rkGalleryGrid.js
- src/components/gallery/rkGalleryImage.js
- src/components/image/rkModalImg.js
- src/components/picker/rkPicker.js
- src/components/switch/rkSwitch.android.js
- src/components/switch/rkSwitch.ios.js
- src/components/tab/rkTabView.js
- src/components/text/rkText.js
- src/components/textinput/rkTextInput.js
> Release v3.1.0

- src/components/avoidKeyboard/rkAvoidKeyboard.js
- src/components/text/rkText.js
* feat(rkText): add prop-types validation
* feat(rkAvoidKeyboard): add prop-types validation
> feat(component): add prop-types validation non-validated components. Closes #93

- CHANGELOG.md
- package.json
- src/components/avoidKeyboard/rkAvoidKeyboard.js
* Add RkAvoidKeyboard deprecation docs
> Release v3.1.1

- CHANGELOG.md
- example/screens/SwitchScreen.js
- src/components/switch/rkSwitch.android.js
- src/components/switch/rkSwitch.ios.js
* fix(rkSwitch): onValueChange parameters not passed to android component
> fix(rkSwitch): onValueChange parameters not passed to android component

- CHANGELOG.md
- package.json
* update changelog
* bump package version to 3.1.2
> bump version to 3.1.2

- docs/assets/articles/index.md
This pull-request fixes a typo at index.md file
> Fix documentation typo at index

- .travis.yml
- README.md
- package.json
- scripts/ci/travis-ci-script.sh
[Travis-CI](https://travis-ci.com/) initial integration
> feat(ci): travis ci integration

- CONTRIBUTING.md
- DEV_DOCS.md
* update dev docs
* update contributing docs
> fix(docs): update dev and contributing guides

- .npmignore
* Update npmignore to ignore ide and git-specific files
> fix(package): update npmignore. Closes #179

- example/README.md
> fix example app readme. Closes #189

- .coveralls.yml
- .travis.yml
- README.md
- jest.config.js
- package.json
* Integrates [coveralls](coveralls.io)
* refactors readme badge links
> feat(ci): integrates coveralls

- src/framework/theme/component/mapping/type.ts
- src/framework/theme/component/style/styleProvider.component.tsx
- src/framework/theme/index.ts
- src/framework/theme/service/mappingUtil.service.ts
- src/framework/theme/service/themeUtil.service.tsx
- src/framework/theme/tests/config.ts
- src/framework/theme/tests/mapping.spec.tsx
- src/framework/theme/tests/style.spec.tsx
- src/framework/theme/tests/theme.spec.tsx
- src/playground/src/app.component.tsx
- src/playground/src/theme-token/index.ts
- src/playground/src/theme-token/mapping.json
* simplifies mapping.json
* adopts tests and sources
> refactor(theme): simplify theme mapping config

- src/framework/theme/component/mapping/type.ts
- src/framework/theme/component/style/styleConsumer.component.tsx
- src/framework/theme/service/mappingUtil.service.ts
- src/framework/theme/service/themeUtil.service.tsx
- src/framework/theme/tests/config.ts
- src/framework/theme/tests/mapping.spec.tsx
- src/framework/theme/tests/style.spec.tsx
- src/framework/theme/tests/theme.spec.tsx
- src/playground/src/theme-token/mapping.json
- src/playground/src/theme-token/theme.json
- src/playground/src/ui/component/sample.component.tsx
- src/playground/src/ui/screen/sample.component.tsx
* add ability to override style using `state` object in mappings
* playground example in `sample` component
* test coverage
> feat(theme): state mappings

- src/framework/ui/index.ts
- src/framework/ui/radioGroup/radioGroup.component.tsx
- src/framework/ui/radioGroup/radioGroup.spec.config.ts
- src/framework/ui/radioGroup/radioGroup.spec.tsx
- src/playground/src/ui/screen/index.ts
- src/playground/src/ui/screen/radioGroup.component.tsx
* implements `RadioGroup` component
> feat(ui): radio group component

- docs/app/docs/utils/analytics.service.ts
- docs/index.html
> chore: update google analytics to GTM

- package-lock.json
- package.json
- src/framework/theme/service/style/styleConsumer.service.ts
- src/framework/ui/index.ts
- src/framework/ui/layout/layout.component.tsx
- src/framework/ui/layout/layout.spec.config.ts
- src/framework/ui/layout/layout.spec.tsx
- src/framework/ui/layout/layout.spec.tsx.snap
- src/playground/src/app.component.tsx
- src/playground/src/ui/screen/index.ts
- src/playground/src/ui/screen/layout.component.tsx
> feat(ui): layout component

- src/framework/ui/index.ts
- src/framework/ui/text/text.component.tsx
- src/playground/src/ui/screen/index.ts
- src/playground/src/ui/screen/text.component.tsx
> feat(ui): text component

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.config.ts
- src/framework/ui/button/button.spec.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/button/type.ts
- src/framework/ui/index.ts
- src/playground/metro.config.js
- src/playground/src/ui/screen/button.component.tsx
- src/playground/src/ui/screen/dialog.component.tsx
- src/playground/src/ui/screen/index.ts
* Integrates button component
* Fixes bundler and compiler issues which where revealed during merge 😞
> feat(ui): button component. Closes #260

- src/components/choice/rkChoice.js
fix: onChange has to pass the current reflected state of selected. see https://github.com/akveo/react-native-ui-kitten/issues/229
> rkChoice onChange #229

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/buttonGroup/buttonGroup.component.tsx
- src/framework/ui/buttonGroup/buttonGroup.spec.config.ts
- src/framework/ui/buttonGroup/buttonGroup.spec.tsx
- src/framework/ui/buttonGroup/type.ts
- src/framework/ui/index.ts
- src/playground/src/ui/screen/buttonGroup.component.tsx
- src/playground/src/ui/screen/index.ts
* Includes several bug fixes for `Button` component
* Implements `ButtonGroup` component
> feat(ui): button-group component. Closes #290

- src/framework/theme/component/application/application.spec.config.ts
- src/framework/theme/component/style/style.spec.config.ts
- src/framework/theme/service/style/style.spec.config.ts
- src/framework/ui/button/button.spec.config.ts
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/buttonGroup/buttonGroup.component.tsx
- src/framework/ui/buttonGroup/buttonGroup.spec.config.ts
- src/framework/ui/checkbox/checkbox.spec.config.ts
- src/framework/ui/modal/modal.spec.tsx.snap
- src/framework/ui/radio/radio.spec.config.ts
- src/framework/ui/radioGroup/radioGroup.spec.config.ts
- src/framework/ui/toggle/toggle.spec.config.ts
- src/playground/src/ui/screen/buttonGroup.component.tsx
> refactor(framework): update .spec configuration files

- src/framework/ui/avatar/avatar.component.tsx
- src/framework/ui/avatar/avatar.spec.config.ts
- src/framework/ui/avatar/avatar.spec.tsx
- src/framework/ui/avatar/avatar.spec.tsx.snap
- src/framework/ui/index.ts
- src/playground/src/ui/screen/avatar.component.tsx
- src/playground/src/ui/screen/index.ts
* Integrates `Avatar` component
> feat(ui): avatar component

- src/framework/ui/radio/radio.component.tsx
- src/framework/ui/radio/radio.spec.config.ts
- src/framework/ui/radio/radio.spec.tsx.snap
- src/framework/ui/radioGroup/radioGroup.spec.config.ts
- src/playground/src/ui/screen/radio.component.tsx
* Add `text` support for `Radio` component
> feat(ui): radio - add text support

- src/framework/ui/drawable/checkmark/checkmark.component.tsx
- src/framework/ui/toggle/toggle.component.tsx
- src/framework/ui/toggle/toggle.spec.tsx.snap
- src/playground/src/ui/screen/toggle.component.tsx
> refactor(ui): toggle icon refactor

- src/components/choiceGroup/rkChoiceGroup.js
> fix(choice-group): Fix incorrect increment of rkChoice children index

- src/framework/theme/index.ts
- src/framework/theme/service/index.ts
- src/framework/theme/service/props/index.ts
- src/framework/theme/service/props/props.service.ts
- src/framework/theme/service/props/props.spec.ts
- src/framework/ui/avatar/avatar.component.tsx
- src/framework/ui/button/button.component.tsx
- src/framework/ui/checkbox/checkbox.component.tsx
- src/framework/ui/common/props.ts
- src/framework/ui/common/type.ts
- src/framework/ui/index.ts
- src/framework/ui/input/input.component.tsx
- src/framework/ui/input/input.spec.tsx
- src/framework/ui/list/listItem.component.tsx
- src/playground/src/ui/screen/list.component.tsx
- src/playground/src/ui/screen/listItem.showcase.component.tsx
This pr will contain fixes and improvements described in #332
> feat: enhancements

- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/input/input.spec.tsx.snap
- src/framework/ui/list/list.spec.tsx
- src/framework/ui/list/list.spec.tsx.snap
- src/framework/ui/overflowMenu/overflowMenu.component.tsx
- src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
- src/playground/src/app.component.tsx
* Fixes overflow-menu `onPress` args
* Fixes list onPress test
* Updates UI test snapshots
* Updates `react-navigation` to 3.0.9
> feat(framework): enhancements

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/common/mapping.json
- src/playground/src/app.component.tsx
* updates button to apply mappings
* updates snapshots
* updates common `mapping.json` used for tests
> refactor(ui): button eva mappings

- src/framework/ui/common/mapping.json
- src/framework/ui/list/list.spec.tsx.snap
- src/framework/ui/list/listItem.component.tsx
> refactor(ui): apply list mappings

- src/framework/ui/common/mapping.json
- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/popover/popoverView.component.tsx
- src/playground/src/ui/screen/popover.component.tsx
> refactor(ui): apply popover mappings

- src/framework/ui/common/mapping.json
- src/framework/ui/overflowMenu/overflowMenu.component.tsx
- src/framework/ui/overflowMenu/overflowMenu.spec.tsx
- src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
- src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
> refactor(ui): apply overflow-menu mappings

- src/framework/ui/common/mapping.json
- src/framework/ui/tab/tab.component.tsx
- src/framework/ui/tab/tab.spec.tsx.snap
- src/playground/src/ui/screen/tabView.component.tsx
> refactor(ui): apply tab mappings

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/common/mapping.json
> refactor(ui): button - apply mappings

- src/framework/ui/common/mapping.json
- src/framework/ui/input/input.component.tsx
- src/framework/ui/input/input.spec.tsx.snap
- src/playground/src/ui/screen/input.component.tsx
> refactor(ui): apply input mappings

- src/framework/ui/checkbox/checkbox.component.tsx
- src/framework/ui/checkbox/checkbox.spec.tsx.snap
- src/framework/ui/common/mapping.json
- src/framework/ui/drawable/checkmark/checkmark.component.tsx
- src/playground/src/ui/screen/checkbox.component.tsx
> refactor(ui): apply checkbox mappings

- src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
- src/framework/ui/bottomNavigation/bottomNavigation.spec.tsx.snap
- src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
- src/framework/ui/common/mapping.json
> refactor(ui): apply bottom-navigation mappings

- src/framework/ui/avatar/avatar.spec.tsx.snap
- src/framework/ui/common/mapping.json
- src/playground/src/ui/screen/avatar.component.tsx
> refactor(ui): apply avatar mappings

- CHANGELOG.md
- example/screens/calendar/BaseCalendarScreen.js
- example/screens/calendar/BoundingCalendarScreen.js
- example/screens/calendar/CustomCalendarScreen.js
- example/screens/calendar/HorizontalCalendarScreen.js
- example/screens/calendar/RangeCalendarScreen.js
- package.json
- src/components/choiceGroup/rkChoiceGroup.js
- src/components/textinput/rkTextInput.js
> release: v3.1.3

- src/framework/ui/package-lock.json
- src/framework/ui/topNavigation/topNavigation.component.tsx
- src/framework/ui/topNavigation/topNavigation.spec.tsx.snap
- src/framework/ui/topNavigation/type.ts
Fixes center alignment on `TopNavigation`
> fix(ui): top-navigation align

- package-lock.json
- src/framework/ui/common/mapping.json
- src/framework/ui/input/input.component.tsx
- src/framework/ui/input/input.spec.tsx
- src/framework/ui/input/input.spec.tsx.snap
- src/playground/package-lock.json
- src/playground/src/ui/screen/input.component.tsx
* ability to add label implemented
* ability to add caption/caption-image implemented
* "size" issues fixed
> feat(ui): input labels

- src/framework/ui/tab/tab.component.tsx
- src/framework/ui/tab/tab.spec.tsx
- src/framework/ui/tab/tabBar.component.tsx
- src/framework/ui/tab/tabBarIndicator.component.tsx
- src/framework/ui/tab/tabView.component.tsx
- src/framework/ui/viewPager/viewPager.component.tsx
- src/framework/ui/viewPager/viewPager.spec.tsx
- src/playground/src/ui/screen/viewPager.component.tsx
* Refactors `ViewPager` to not accept `contentWidth` prop
* Adds ability to style text in `Tab`
> refactor(ui): tab-view enhancements

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/button/type.ts
- src/framework/ui/index.ts
- src/framework/ui/input/input.component.tsx
- src/framework/ui/input/input.spec.tsx.snap
- src/playground/src/ui/screen/button.component.tsx
* button content alignment fixed
* input interactions with containers fixed
> fix(ui): container component interactions

- src/framework/ui/common/mapping.json
- src/framework/ui/toggle/toggle.component.tsx
- src/framework/ui/toggle/toggle.spec.tsx
- src/framework/ui/toggle/toggle.spec.tsx.snap
- src/playground/src/ui/screen/toggle.component.tsx
* Refactors `Toggle` to apply eva style
> refactor(mapping): update toggle mapping

- src/framework/theme/component/style/style.spec.tsx
- src/framework/theme/component/style/styleConsumer.component.tsx
- src/framework/ui/avatar/avatar.component.tsx
- src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
- src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
- src/framework/ui/button/button.component.tsx
- src/framework/ui/buttonGroup/buttonGroup.component.tsx
- src/framework/ui/checkbox/checkbox.component.tsx
- src/framework/ui/index.ts
- src/framework/ui/input/input.component.tsx
- src/framework/ui/layout/layout.component.tsx
- src/framework/ui/list/list.component.tsx
- src/framework/ui/list/listItem.component.tsx
- src/framework/ui/overflowMenu/overflowMenu.component.tsx
- src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/radio/radio.component.tsx
- src/framework/ui/radioGroup/radioGroup.component.tsx
- src/framework/ui/tab/tab.component.tsx
- src/framework/ui/tab/tabBar.component.tsx
- src/framework/ui/tab/tabView.component.tsx
- src/framework/ui/text/text.component.tsx
- src/framework/ui/toggle/toggle.component.tsx
- src/framework/ui/tooltip/tooltip.component.tsx
- src/framework/ui/topNavigation/topNavigation.component.tsx
- src/framework/ui/topNavigation/topNavigationAction.component.tsx
* This resolves production issue when components are unable to find corresponding mappings (caused by code minifying)
> fix(ui): mapping find issues

- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/popover/type.spec.ts
- src/framework/ui/popover/type.ts
> fix(ui): popover margins offsets fix

- src/framework/ui/common/mapping.json
- src/framework/ui/input/input.spec.tsx.snap
> fix(ui): update input mappings

- src/framework/ui/viewPager/viewPager.component.tsx
- src/playground/src/ui/screen/viewPager.component.tsx
> fix(ui): view-pager swipe fix 

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/common/mapping.json
> fix(ui): button layout issues

- src/framework/ui/button/button.component.tsx
- src/framework/ui/button/button.spec.tsx
- src/framework/ui/button/button.spec.tsx.snap
- src/framework/ui/common/props.ts
> feat(ui): button "textStyle" property add

- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/popover/type.spec.ts
- src/framework/ui/popover/type.ts
* Fixes popover position in scrollable container
> fix(ui): popover - scrollable container

- src/framework/ui/popover/type.ts
> fix(ui): popover - crash when no styles

- src/framework/ui/list/listItem.component.tsx
* Allows overriding `activeOpacity`
> fix(ui): list-item style

- src/framework/theme/application/applicationProvider.component.tsx
- src/framework/theme/style/styleConsumer.component.tsx
- src/framework/theme/theme/themeConsumer.component.tsx
Documents following `theme` components:
* `ApplicationProvider`
* `styled` HOC
* `withStyles` HOC
> docs(theme): add theme components documentation

- docs/src/app/@theme/services/structure.service.ts
- docs/src/articles/index.md
- docs/src/guides/index.md
- docs/src/guides/install-into-existing.md
- docs/src/guides/start.md
- docs/src/guides/theme-customize-component.md
- docs/src/guides/theme-system.md
- docs/src/guides/theme-using-mapping.md
- docs/src/guides/theme-using-variables.md
- docs/src/structure.ts
- src/playground/src/app.component.tsx
Adds following guides:
* `What is React Native UI Kitten?`
* `Getting Started` and installation flow
* Theme System and usage
> docs(guides): add getting-started and theme-system guides

- src/framework/ui/avatar/avatar.component.tsx
- src/framework/ui/topNavigation/topNavigation.component.tsx
- src/framework/ui/topNavigation/topNavigationAction.component.tsx
* Allows setting avatar `borderRadius`
* Fixes top navigation action style
> fix(ui): common issues

- src/framework/ui/topNavigation/topNavigation.component.tsx
* Fixes top-navigation style apply
> fix(ui): top-navigation style apply

- src/framework/ui/checkbox/checkbox.component.tsx
- src/framework/ui/radio/radio.component.tsx
- src/framework/ui/radio/radio.spec.tsx.snap
- src/framework/ui/support/tests/mapping.json
> refactor(ui): radio/button hit-slopes add

- src/framework/ui/popover/popover.component.tsx
> fix(ui): popover position

- src/framework/ui/overflowMenu/overflowMenu.component.tsx
- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/popover/popoverView.component.tsx
- src/framework/ui/tooltip/tooltip.component.tsx
* Adds `indicatorStyle` property to `Popover`
* Applies eva mapping on popover-based components
> feat(ui): popover indicator style

- src/framework/theme/style/styleConsumer.component.tsx
- src/framework/theme/theme/themeConsumer.component.tsx
* Adds ability to pass functional component to `style` HOCs with no TS complains
> fix(theme): style HOCs component arg type

- package-lock.json
- package.json
- src/playground/package-lock.json
- src/playground/package.json
- src/playground/src/ui/screen/common/showcase.component.tsx
> build(common): update eva dependencies

- .travis.yml
- package.json
* Refactors travis scripts to run with special ci environment
> refactor(script): travis-ci scripts

- src/framework/ui/viewPager/viewPager.component.tsx
* Fixes ViewPager scroll event dispatching on Android
Issue: https://github.com/facebook/react-native/issues/21718
> fix(ui): view-pager scroll event on android

- src/framework/ui/buttonGroup/buttonGroup.component.tsx
> fix(ui): button-group dividers

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- DEV_DOCS.md
> docs(common): fix DEV_DOCS, CODE_OF_CONDUCT, CONTRIBUTING

- package-lock.json
- package.json
- src/framework/package.json
- src/playground/package-lock.json
- src/playground/package.json
> build(common): bump eva version to 1.0.0

- package.json
- src/framework/package.json
* Bumps framework version to 4.0.1
> release: v4.0.1

- docs/src/app/@theme/styles/styles.scss
> fix: prevent header disappearing when selecting version

- docs/src/landing/css/reactive-kitten.webflow.css
- docs/src/landing/index.html
> fix(docs): ie fixes

- docs/src/landing/css/reactive-kitten.webflow.css
> fix(docs): make menu button clickable

- src/framework/ui/topNavigation/topNavigationAction.component.tsx
> fix(top-navigation): add hit-slop to actions

- README.md
- docs/src/guides/theme-switching.md
- docs/src/guides/theme-system.md
- docs/src/guides/theme-using-mapping.md
- src/framework/theme/application/applicationProvider.component.tsx
Fixes theme import typo in documentation guides. Requires gh-pages update
Closes #440
> fix(docs): theme import typo

- docs/app/docs/docs.component.ts
> fix(docs): proper demo url

- docs/src/app/@theme/components/header/header.component.ts
- docs/src/app/@theme/components/search/search.component.ts
> docs: add algolia search

- src/framework/ui/toggle/toggle.component.tsx
The Toggle component documentation is wrong about the props the component receives
> Update toggle component doc and example

- package-lock.json
- package.json
- src/framework/ui/support/typings/type.ts
- src/playground/package-lock.json
- src/playground/package.json
Fixes TouchableIndexedProps declaration. Closes #462
> build: fix typescript build errors

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/package.json
> release: v4.0.3

- jest.config.js
- tsconfig.dev.json
- tsconfig.json
- tsconfig.prod.json
- tsconfig.test.json
* Fixes typescript build warnings like missing `esModuleInterop` flag
> build(common): typescript common issues

- src/framework/ui/toggle/toggle.component.tsx
> fix(docs): toggle docs fix

- src/framework/ui/checkbox/checkbox.component.tsx
Fixes `CheckBox` usage documentation
Closes #482
> fix(ui): checkbox usage docs

- src/framework/ui/input/input.component.tsx
- src/framework/ui/input/input.spec.tsx
Adds `Input` API methods:
- `blur`
- `focus`
- `isFocused`
- `clear`
Closes #479
> fix(ui): add input api methods

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/package.json
- src/playground/package-lock.json
> release: v4.0.4

- README.md
Fixes Design System guide link in README.md
> docs(readme): update design system link

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/package.json
- src/playground/package-lock.json
> release: v4.0.5

- src/framework/ui/input/input.component.tsx
- src/framework/ui/input/input.spec.tsx
* Closes #451 
This is a temporary solution to resolve this. We need to go back to this and resolve this with Eva Design System - https://github.com/eva-design/eva/issues/19
> feat(ui): input - icon press handler

- docs/src/articles/design-system/custom-mapping.md
* Expands custom mapping guide with example code on passing mapping variants
> feat(docs): expand custom-mapping guide

- package-lock.json
- package.json
> refactor(docs): docs prsr version update

- docs/src/articles/guides/create-screen.md
> docs(guides): fix create-screen import typo

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/package.json
- src/playground/package-lock.json
> release: v4.1.0

- docs/src/landing/css/reactive-kitten.webflow.css
> fix(docs): landing style fix

- docs/src/app/@theme/styles/styles.scss
- docs/src/app/blocks/blocks.module.ts
- docs/src/app/blocks/components/code-block/code-block.component.scss
- docs/src/app/blocks/components/index.ts
- docs/src/app/blocks/components/overview-block/overview-block.component.ts
- docs/src/app/blocks/components/overview-example-block/overview-example-block.component.ts
- package-lock.json
- package.json
- src/framework/ui/button/button.component.tsx
- src/framework/ui/modal/modal.component.tsx
- docs-prsr updated
- overview-examples docs component added
> feat(docs): overview-examples handling add

- src/framework/ui/modal/modal.component.tsx
> fix(ui): modal docs fix

- src/framework/ui/popover/placement.service.ts
- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/popover/type.spec.ts
- src/framework/ui/popover/type.ts
* Implements popover automatic positioning. This means if it receives placement set to `right` but there is no enough space on the screen to be displayed, it will render on the left, etc. :tada:
Closes #258
> feat(ui): popover - autoplacement

- src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
> refactor(ui): bottom-navigation documentation update

- src/framework/theme/modal/modal.service.tsx
- src/framework/theme/modal/modalPanel.component.tsx
- src/framework/ui/modal/modal.component.tsx
- src/framework/ui/modal/modal.spec.tsx
- src/framework/ui/popover/popover.component.tsx
- src/framework/ui/support/typings/type.ts
- src/playground/package-lock.json
> feat(ui/theme): "modal-team" missing update functionality add

- src/framework/ui/viewPager/viewPager.component.tsx
> fix(ui): view-pager - external state control

- src/framework/ui/select/select.component.tsx
- src/framework/ui/support/tests/mapping.json
- select eva-styles names refactor
> refactor(ui): select styles names refactor

- src/framework/ui/modal/modal.component.tsx
> fix(ui): modal invisible element pointer events disable

- CHANGELOG.md
- package-lock.json
- package.json
- src/eva-icons/package.json
- src/framework/package.json
- src/templates/template-ui-kitten-typescript/dependencies.json
- src/templates/template-ui-kitten-typescript/package.json
- src/templates/template-ui-kitten/dependencies.json
- src/templates/template-ui-kitten/package.json
> release: v4.2.0-beta.2

- src/framework/ui/checkbox/checkbox.component.tsx
- src/framework/ui/drawer/drawer.component.tsx
- src/framework/ui/icon/icon.component.tsx
- src/framework/ui/layout/layout.component.tsx
- src/framework/ui/select/select.component.tsx
- src/framework/ui/spinner/spinner.component.tsx
> refactor(docs): drawer/icon/select/spinner documentation refactor

- src/framework/ui/overflowMenu/overflowMenu.component.tsx
Fixes references in OverflowMenu examples
> refactor(docs): OverflowMenu example changed

- src/framework/ui/select/select.component.tsx
- src/framework/ui/select/selection.strategy.ts
* Fixes `Select`s `selectedOption` prop change
> fix(ui): select - selectedOption value change

- src/framework/ui/input/input.component.tsx
> refactor(docs): input docs expand

- docs/src/articles/guides/install-new.md
fix missing app name in the documentation example
> fix example in documentation

- src/framework/ui/modal/modal.component.tsx
> fix(ui): modal with backdrop update functionality refactor

- src/framework/ui/modal/modal.component.tsx
Fixes modal `backdropStyle` property definition
> refactor(ui): modal - backdrop style prop definition

- docs/src/structure.ts
- scripts/gulp/tasks/docs/docs.ts
- src/framework/ui/drawer/drawer.component.tsx
- src/framework/ui/drawer/drawerHeaderFooter.component.tsx
* Updates `Drawer` & `DrawerHeaderFooter` documentation
> docs(components): update drawer documentation

- src/framework/ui/topNavigation/topNavigation.component.tsx
- Adds top-navigation with menu example
> docs(components): add top-navigation with menu example

- docs/src/articles/getting-started/what-is-ui-kitten.md
Mentions `@ui-kitten/eva-icons` module in "What is UI Kitten?" guide
> docs(getting-started): add @ui-kitten/eva-icons to what-is guide

- src/playground/src/ui/screen/overflowMenu/overflowMenuShowcase.component.tsx
- src/playground/src/ui/screen/showcases/overflowMenu/overflowMenuAppearance.component.tsx
- src/playground/src/ui/screen/showcases/overflowMenu/overflowMenuExternalSourceIcons.component.tsx
- src/playground/src/ui/screen/showcases/overflowMenu/overflowMenuSimpleUsage.component.tsx
- src/playground/src/ui/screen/showcases/overflowMenu/overflowMenuWithDisabledItems.component.tsx
- src/playground/src/ui/screen/showcases/overflowMenu/overflowMenuWithIcons.component.tsx
This fixes `OverflowMenu` showcases unexpected width changes when selecting an item with simply closing it :)
> docs(components): fix overflow-menu showcases

- src/playground/src/ui/screen/calendar/calendarCustomItem.component.tsx
- src/playground/src/ui/screen/calendar/type.ts
- src/playground/src/ui/screen/showcases/calendar/calendarBoundingMonth.component.tsx
- src/playground/src/ui/screen/showcases/calendar/calendarCustomDay.component.tsx
- src/playground/src/ui/screen/showcases/calendar/calendarCustomLocale.component.tsx
- src/playground/src/ui/screen/showcases/calendar/calendarFilterShowcase.component.tsx
- src/playground/src/ui/screen/showcases/calendar/calendarMoment.component.tsx
- src/playground/src/ui/screen/showcases/calendar/calendarSimpleUsage.component.tsx
This fixes calendar showcases with replacing centering styles
> docs(components): fix calendar showcases

- docs/src/app/@theme/styles/styles.scss
- docs/src/app/blocks/blocks.module.ts
- docs/src/app/blocks/components/live-example-block/live-example-block.component.html
- docs/src/app/blocks/components/live-example-block/live-example-block.component.scss
> feat(docs): live-examples warning add

- src/framework/ui/calendar/baseCalendar.component.tsx
- src/framework/ui/calendar/calendar.component.tsx
- src/framework/ui/calendar/components/calendarHeader.component.tsx
- src/playground/src/ui/screen/calendar/type.ts
- src/playground/src/ui/screen/showcases/calendar/calendarBounds.component.tsx
- src/playground/src/ui/screen/showcases/calendar/index.ts
- Closes #680 
- Adds this showcase to documentation
- Refactors playground example
> fix(ui): calendar min-max navigation

- src/date-fns/dateFnsDate.service.spec.ts
- src/date-fns/dateFnsDate.service.ts
- src/framework/ui/calendar/calendar.component.tsx
- src/framework/ui/calendar/service/nativeDate.service.spec.ts
- src/framework/ui/calendar/service/nativeDate.service.ts
- src/framework/ui/index.ts
- src/playground/src/ui/screen/calendar/type.ts
- src/playground/src/ui/screen/showcases/calendar/calendarCustomLocale.component.tsx
- src/playground/src/ui/screen/showcases/calendar/calendarStartDayOfWeek.component.tsx
- src/playground/src/ui/screen/showcases/calendar/index.ts
- Closes #682
- Adds documentation feature showcases
> feat(ui): calendar - start day of week

- CHANGELOG.md
- package-lock.json
- package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/framework/package.json
- src/moment/package.json
- src/playground/package-lock.json
- src/playground/package.json
- src/templates/template-ui-kitten-typescript/package.json
- src/templates/template-ui-kitten-typescript/template/package.json
- src/templates/template-ui-kitten/package.json
- src/templates/template-ui-kitten/template/package.json
> release: v4.3.0-beta.1

- src/framework/ui/calendar/baseCalendar.component.tsx
> fix(ui): calendar - date bounds disabling behavior

- docs/src/articles/guides/install-new.md
Change`...React Native CLI tools ant UI Kitten template.` to `...React Native CLI tools and UI Kitten template`.
>  fix: typo

- docs/src/articles/guides/create-screen.md
- docs/src/articles/guides/setup-icons-module.md
- docs/src/articles/guides/setup-vector-icons.md
- docs/src/articles/guides/using-web.md
- src/framework/theme/style/styleConsumer.service.ts
> docs(guides): fix application provider guide link

- docs/src/structure.ts
- src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
- src/framework/ui/drawer/drawer.component.tsx
- src/framework/ui/tab/tabBar.component.tsx
Unifies `Using with React Navigation` examples for navigation components
> docs(components): unify react-navigation samples

- src/framework/ui/list/list.component.tsx
> fix(ui): list - add ability to override keyExtractor

- src/framework/ui/calendar/calendar.spec.tsx
- src/framework/ui/calendar/rangeCalendar.spec.tsx
- src/framework/ui/calendar/service/nativeDate.service.spec.ts
- src/framework/ui/calendar/service/nativeDate.service.ts
- src/framework/ui/calendar/service/rangeDate.service.spec.ts
This fixes calendar pagination for users on a negative time zone.
Thanks to @wrsulliv for the [detailed description](https://github.com/akveo/react-native-ui-kitten/pull/714#issuecomment-549158362).
- Closes #712
- Closes #713
> fix(ui): calendar - replace UTC dates with regular dates

- src/framework/ui/calendar/baseCalendar.component.tsx
- src/framework/ui/calendar/calendar.component.tsx
- src/framework/ui/calendar/rangeCalendar.component.tsx
- src/framework/ui/datepicker/baseDatepicker.component.tsx
- src/framework/ui/datepicker/datepicker.component.tsx
- src/framework/ui/datepicker/datepicker.spec.tsx
- src/framework/ui/datepicker/rangeDatepicker.component.tsx
- src/framework/ui/datepicker/rangeDatepicker.spec.tsx
- src/framework/ui/index.ts
- src/framework/ui/input/input.component.tsx
- src/playground/src/ui/screen/datepicker/datepicker.container.tsx
- src/playground/src/ui/screen/datepicker/datepickerShowcase.component.tsx
- src/playground/src/ui/screen/datepicker/rangeDatepickerShowcase.component.tsx
* Closes #721 
* Simplifies calendar and date-picker type definitions
> feat(ui): datepicker - add placeholder property

- docs/src/landing/index.html
> chore(docs): add Eva black friday deal

- docs/src/landing/index.html
> chore(docs): change Black Friday to Cyber Monday

- CHANGELOG.md
- package.json
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
> release: v4.3.0

- package.json
- src/components/package.json
- src/template-js/template/package.json
- src/template-ts/template/package.json
- yarn.lock
> chore: update eva to 1.3

- README.md
- scripts/publish-packages.ts
> docs(readme): update quick-start section

- tsconfig.json
> fix: typescript build issues

- CHANGELOG.md
- package.json
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/playground/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
> release: v4.3.1

- README.md
- docs/src/landing/index.html
> chore(docs): remove deals text

- docs/src/articles/guides/getting-started.md
Typo in 'Configure Application Root' secition of the [Getting Started](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation) guide
> docs: fix typo

- CHANGELOG.md
- package.json
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/playground/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
- yarn.lock
> release: v4.3.2

- src/components/ui/calendar/calendar.spec.tsx
- src/components/ui/calendar/rangeCalendar.spec.tsx
> test(components): update calendar tests

- CHANGELOG.md
- package.json
- scripts/parse-docs.ts
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/playground/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
- yarn.lock
> release: v4.4.0-beta.1

- CHANGELOG.md
Anchor was targeting previous release
> Fix link to release

- docs/src/articles/guides/icon-packages.md
It fix a wrong React.Fragment closing tag inside the doc.
> Fix React.Fragment closing tag

- src/components/ui/autocomplete/autocomplete.component.tsx
- src/showcases/components/autocomplete/autocompleteStates.component.tsx
Closes #800 
Related PR (demo app) - https://github.com/akveo/kittenTricks/pull/257
> fix(components): autocomplete - android runtime crash

- src/components/ui/autocomplete/autocomplete.component.tsx
- src/components/ui/datepicker/baseDatepicker.component.tsx
- src/components/ui/datepicker/datepicker.component.tsx
- src/components/ui/datepicker/rangeDatepicker.component.tsx
- src/components/ui/input/input.component.tsx
- src/components/ui/select/select.component.tsx
Closes #801
Closes #802
Related PR (mapping) - eva-design/eva#60
Related PR (demo app) - https://github.com/akveo/kittenTricks/pull/257
> feat(components): add direct manipulation methods to input components

- docs/src/app/documentation/documentation.component.html
> chore(docs): replace email with SO and GitHub links

- src/components/ui/select/select.component.tsx
- src/components/ui/select/selectOptionsList.component.tsx
> fix(components): select - vertical scroll indicator

- .github/workflows/continuous-integration-workflow.yml
> chore: update github-actions workflow name to fix readme badge

- src/components/ui/input/input.component.tsx
> fix(components): input - placeholderTextColor

- CHANGELOG.md
- package.json
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/showcases/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
- yarn.lock
> release: v4.4.0-beta.2

- src/showcases/components/showcaseIFrame.component.tsx
Fixes theme switcher in documentation live examples
> docs(showcases): fix theme switcher

- CHANGELOG.md
- package.json
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/showcases/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
> release: v4.4.0-beta.3

- src/components/ui/modal/modal.component.tsx
> fix(components): modal - state update during render

- src/components/ui/datepicker/baseDatepicker.component.tsx
- src/components/ui/datepicker/datepicker.component.tsx
- src/components/ui/datepicker/rangeDatepicker.component.tsx
Adds `backdropStyle` property to Datepicker and RangeDatepicker components
Closes #849
> feat(components): datepicker - add backdropStyle prop

- src/components/ui/input/input.component.tsx
For any reason, this bug is not producible within Expo environment
Closes #609
> fix(components): input - size on android

- src/components/ui/autocomplete/autocomplete.component.tsx
- src/components/ui/datepicker/datepicker.component.tsx
- src/components/ui/datepicker/rangeDatepicker.component.tsx
- src/components/ui/overflowMenu/overflowMenu.component.tsx
- src/components/ui/popover/popover.component.tsx
- src/components/ui/tooltip/tooltip.component.tsx
- src/showcases/components/autocomplete/autocompleteHandleKeyboard.component.tsx
Adds `placement` property to Autocomplete and fixes documentation typos for this prop in scope of other components.
Closes #845
> feat(components): autocomplete - add placement property

- src/components/ui/datepicker/baseDatepicker.component.tsx
- src/components/ui/datepicker/datepicker.component.tsx
- src/components/ui/datepicker/rangeDatepicker.component.tsx
- src/components/ui/select/select.component.tsx
> feat(components): add onFocus and onBlur props to input-based components

- docs/src/articles/design-system/use-theme-variables.md
Fix documentation for akveo#464 and akveo#871
Closes #871
> fix(docs): fix example usage of theme variable

- docs/src/articles/guides/icon-packages.md
Adds guide on integration Icon component with asset images
> docs(guides): add asset icons pack guide

- CHANGELOG.md
- package.json
- src/components/package.json
- src/date-fns/package.json
- src/eva-icons/package.json
- src/moment/package.json
- src/showcases/package.json
- src/template-js/package.json
- src/template-js/template/package.json
- src/template-ts/package.json
- src/template-ts/template/package.json
- yarn.lock
> release: v4.4.0

- src/components/ui/tab/tabView.component.tsx
- src/components/ui/viewPager/viewPager.component.tsx
- src/showcases/package.json
- yarn.lock
Fixes documentation showcase application build and typescript issues for `@ui-kitten/components` package
> fix: typescript and expo build issues

- src/components/ui/select/select.component.tsx
> fix(components): select - make onFocus and onBlur properties optional

- docs/src/articles/guides/configure-navigation.md
- src/components/ui/bottomNavigation/bottomNavigation.component.tsx
- src/components/ui/drawer/drawer.component.tsx
- src/components/ui/tab/tabBar.component.tsx
Updates configure navigation guide and navigation components usage examples to React Navigation v5
> docs(guides): update configure navigation guide

- docs/src/articles/guides/getting-started.md
- docs/src/structure.ts
- src/components/ui/input/input.component.tsx
- Remove not existing live example of Input
- Fix start script in Getting Started
- Fix ThemedComponent icon
> docs: fix several minor issues

- docs/src/structure.ts
- package.json
- scripts/create-doc-themes.ts
- scripts/parse-docs.ts
- src/showcases/app/app.component.tsx
- src/showcases/app/themes.ts
- src/showcases/components/showcaseIFrame.component.tsx
- src/showcases/services/theme.service.ts
- yarn.lock
> docs(showcases): add material themes to theme switcher

- scripts/publish-docs.ts
> docs: fix copy old version script

- docs/src/articles/guides/branding.md
> docs: fix light-theme link to eva-light-theme

- docs/src/articles/guides/configure-navigation.md
This PR removes duplicated word "documentation" in guides page.
> docs(articles): Remove duplicated word

- docs/src/articles/design-system/customize-mapping.md
> docs(articles): custom mapping - default values guide

- src/components/ui/select/select.component.tsx
> fix(components): select - placeholder style

- src/components/ui/autocomplete/autocomplete.component.tsx
> fix(components): autocomplete - show options on press

- src/components/ui/card/card.component.tsx
> fix(components): card-header - press responder

- src/components/devsupport/components/falsyFC/falsyFC.component.tsx
- src/components/devsupport/components/falsyFC/falsyFC.spec.tsx
- src/components/devsupport/components/falsyText/falsyText.component.tsx
- src/components/devsupport/components/falsyText/falsyText.spec.tsx
> fix(components): FalsyFC should be able to render components with hooks

- docs/package.json
- scripts/docs-dirs.ts
- scripts/gulpfile.ts
- scripts/publish-docs.ts
Create directories in the build folder for each app's page and place index.html in it to avoid 404 errors for better seo.
> chore(docs): mimic docs app structure to avoid 404 errors for better seo

- README.md
> docs(readme): change mobile backend bundle links

- docs/src/app/@theme/components/hubspot-cta/akveo-services-banner.component.scss
- docs/src/app/@theme/components/hubspot-cta/akveo-services-banner.component.ts
- docs/src/app/@theme/theme.module.ts
- docs/src/app/documentation/page/page.component.html
Fixes styles of akveo services banner (move a bit left)
Unify banner component with the same component in nebular docs.
> chore(docs): fix banner alignment

- docs/src/articles/design-system/glossary.md
- docs/src/articles/guides/branding.md
- docs/src/articles/guides/configure-navigation.md
- docs/src/articles/guides/icon-packages.md
Fixes navigation component example and typos in docs . 
Closes #1127 
Closes #1114
> Docs fixes

- src/showcases/components/autocomplete/autocompleteAccessories.component.tsx
You can't use the original index on a filtered list.
Closes #1097
> Fix filtered index issue

- docs/src/app/documentation/page/page.component.ts
- docs/src/structure.ts
> feat(docs): add dynamic meta tags and title for docs pages

- docs/src/app/@theme/styles/themes.scss
- docs/src/app/documentation/page/page.component.html
- docs/src/app/documentation/page/page.component.scss
- docs/src/app/documentation/page/page.component.ts
Add scroll to the right sidebar to make all content visible on small screens.
Use one new akveo services banner image for all pages.
> fix(docs): add scroll to right sidebar

- src/components/ui/tab/tabBar.component.tsx
Fixes a mis-referenced function in the top tabs component documentation.
> fix(docs): Fix incorrect function reference

- README.md
> docs(readme): update twitter url

- docs/src/landing/css/download-dialog.scss
- docs/src/landing/css/reactive-kitten.webflow.css
- docs/src/landing/index.html
- docs/src/landing/js/download-dialog.js
> chore(docs): add download dialog

- src/components/ui/input/input.component.tsx
This fixes #1259 for the documentation of Input component
> Fixed docs for #1259

- src/components/ui/topNavigation/topNavigation.component.tsx
Fixes #1284 by adding additional appropriate styles to containers.
> fix: topNavigation styles

- src/components/ui/viewPager/viewPager.component.tsx
- src/components/ui/viewPager/viewPager.spec.tsx
> feat(view-pager): swipeEnabled prop

- src/components/ui/menu/menu.component.tsx
- src/components/ui/menu/menu.service.ts
- src/components/ui/menu/menu.spec.tsx
- src/components/ui/menu/menuGroup.component.tsx
- src/components/ui/menu/menuItem.component.tsx
Fix for menu onPress event
Closes #1207
> fix: menu onPress event for groups & items

- src/components/ui/buttonGroup/buttonGroup.component.tsx
- src/components/ui/buttonGroup/buttonGroup.spec.tsx
- src/showcases/components/buttonGroup/buttonGroupAppearance.component.tsx
- src/showcases/components/buttonGroup/buttonGroupGhost.component.tsx
[Related eva update.](https://github.com/eva-design/eva/pull/78)
Closes #1151.
> update(buttonGroup): add ghost appearance for buttonGroup component

- src/template-js/package.json
- src/template-ts/package.json
> fix(templates):bump patch version for templates:5.1.1

- README.md
- docs/src/landing/index.html
> docs(readme):update readme and landing

- src/components/ui/icon/icon.component.tsx
- [+] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
- [+] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.
> fix(icon): Fixed warning does not recognise the animationConfig.

- src/components/ui/list/list.component.tsx
> fix(List): forward ItemT to React's ListProps

- src/components/package.json
- src/eva-icons/package.json
> Feat: update peers version

- package.json
- yarn.lock
> fix: update eva packages to v2.1.1

- DEV_DOCS.md
> docs: add template verification steps for release manual

- src/template-js/package.json
- src/template-ts/package.json
> fix: bump templates versions

- package.json
- scripts/parse-docs.ts
> build: add step for docs publishing

- src/components/theme/modal/modal.service.tsx
> fix (modal service): update usage example

- src/components/ui/popover/popover.component.tsx
> fix (popover): block showing after unmount

- src/components/ui/calendar/baseCalendar.component.tsx
- src/components/ui/calendar/calendar.component.tsx
- src/components/ui/calendar/calendar.spec.tsx
- src/components/ui/calendar/rangeCalendar.component.tsx
- src/components/ui/calendar/rangeCalendar.spec.tsx
- src/components/ui/datepicker/baseDatepicker.component.tsx
- src/components/ui/datepicker/datepicker.component.tsx
- src/components/ui/datepicker/datepicker.spec.tsx
- src/components/ui/datepicker/rangeDatepicker.component.tsx
- src/components/ui/datepicker/rangeDatepicker.spec.tsx
- src/showcases/components/calendar/calendarInitialVisibleDate.component.tsx
- src/showcases/components/datepicker/datepickerInitialVisibleDate.component.tsx
The current pull request adds initialVisibleDate (resolves #1563),
adds new api methods scrollToToday, scrollToDate (resolves  #1222).
Also, it fixes styles of today's date by removing today's value from selectedDate.
> feat(calendar): add initialVisibleDate, api to show specific dates, fix styles of today's date.

- docs/src/articles/design-system/use-theme-variables.md
Update docs by adding section with hooks examples on `Design System` part of docs
> update: add to docs part related to design a section with theme hooks examples

- .github/workflows/publish-kitten-tricks.yml
> fix(gh):set node version for publish to expo extension

- src/components/ui/bottomNavigation/bottomNavigation.component.tsx
- src/components/ui/bottomNavigation/bottomNavigation.spec.tsx
- src/components/ui/shared/tabIndicator.component.tsx
- src/components/ui/tab/tab.spec.tsx
- src/components/ui/tab/tabBar.component.tsx
> fix(tabindicator): add a wrapper over the indicator to apply  user styles correctly (#1512)

- src/components/theme/style/style.service.tsx
- src/components/theme/style/style.spec.tsx
- src/components/theme/theme/theme.spec.tsx
- tsconfig.json
Prevent `useStyleSheet()` hook returning same values
Closes #1544
> fix: styles hook memoization

- src/components/ui/modal/modal.component.tsx
> Fix(modal): deprecated warn removed

- src/components/ui/tab/tab.spec.tsx
> fix(tab): fixed tab component tests

- docs/src/articles/guides/branding.md
Is this the correct link? The existing one 404's.
I think this might resolve a broken URL in the branding documentation.
> Update link to sketch file on gum road.

- src/components/ui/datepicker/rangeDatepicker.spec.tsx
- src/components/ui/topNavigation/topNavigation.spec.tsx
Seems maintainers on this repo usually use MacOS daily. And it can be a blocker in the feature for people how wants to contribute on different platforms
> fix(tests): Make tests green on case sensitive file systems

- src/components/ui/card/card.component.tsx
Small adjustment to card component, which should fix images displaying (#1514)
> fix: added shrinking to card children container

- src/components/devsupport/components/falsyFC/falsyFC.spec.tsx
- src/components/devsupport/components/falsyText/falsyText.spec.tsx
- src/components/ui/calendar/calendar.spec.tsx
- src/components/ui/calendar/rangeCalendar.spec.tsx
- src/components/ui/shared/tabIndicator.component.tsx
- src/components/ui/tab/tab.spec.tsx
> fix: check and fixed failing tests

- docs/src/landing/index.html
- src/components/ui/viewPager/viewPager.component.tsx
> release: v5.3.0

- src/components/ui/calendar/components/calendarHeader.component.tsx
> fix: datepicker select month error (#1694, #1687, #1713)

- src/components/ui/popover/popover.component.tsx
> fix: popover props type
